_wandb:
    value:
        cli_version: 0.24.0
        e:
            bwotrhnlxd5whs5nh8nrn6gu437atla2:
                codePath: Week4/train.py
                codePathLocal: train.py
                email: arnaumarcosalmansa@gmail.com
                executable: /ghome/group06/miniconda3/envs/c3/bin/python
                git:
                    commit: 5731f8adfce94e1e648abdc9728f446988f012e5
                    remote: https://github.com/MCV-C3/project-team-6.git
                host: dcc3090
                os: Linux-5.15.0-88-generic-x86_64-with-glibc2.31
                program: /export/home/group06/workspace/project-team-6/Week4/train.py
                python: CPython 3.11.14
                root: .
                startedAt: "2026-01-18T15:35:32.842651Z"
                writerId: bwotrhnlxd5whs5nh8nrn6gu437atla2
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 9
                - 41
                - 103
            "2":
                - 1
                - 9
                - 41
                - 103
            "3":
                - 7
                - 13
                - 66
            "4": 3.11.14
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
architecture:
    value: Small LeNet
epochs:
    value: 500
image_size:
    value: 224
learning_rate:
    value: 0.0001
parameters:
    value: 24328
