_wandb:
    value:
        cli_version: 0.23.1
        e:
            clb1x6meqk0aj692ao5zqhnuepd8b1zq:
                codePath: Week3/train_def.py
                codePathLocal: Week3/train_def.py
                cpu_count: 10
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "223184257024"
                        used: "158882172928"
                email: aleix.armero73@gmail.com
                executable: /home/p3rzival/miniconda3/envs/c3/bin/python
                git:
                    commit: 963806dde4e2a964948626295a36b3ac4df71b14
                    remote: https://github.com/MCV-C3/project-team-6.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-2c146194-548d-9c36-5dc0-d5b19131e6eb
                host: p3rzival
                memory:
                    total: "16447229952"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /home/p3rzival/MCV/project-team-6/Week3/train_def.py
                python: CPython 3.11.14
                root: /home/p3rzival/MCV/project-team-6
                startedAt: "2026-01-10T23:41:59.424856Z"
                writerId: clb1x6meqk0aj692ao5zqhnuepd8b1zq
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 79
            "2":
                - 1
                - 5
                - 41
                - 53
                - 79
            "3":
                - 13
                - 16
            "4": 3.11.14
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
architecture:
    value: DenseNet121-Squeeze-Excitation
epochs:
    value: 500
experiment_type:
    value: Definitive Parameters
image_size:
    value: 224
