_wandb:
    value:
        cli_version: 0.23.1
        e:
            46ywv1h8dg6fgi94varqcy130c9gxap5:
                codePath: Week3/train.py
                codePathLocal: Week3/train.py
                email: aleix.armero73@gmail.com
                executable: /home/p3rzival/miniconda3/envs/c3/bin/python
                git:
                    commit: 07d261e8c271b917c5734a9ee343e33b5b9dc477
                    remote: https://github.com/MCV-C3/project-team-6.git
                host: p3rzival
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /home/p3rzival/MCV/project-team-6/Week3/train.py
                python: CPython 3.11.14
                root: /home/p3rzival/MCV/project-team-6
                startedAt: "2026-01-10T15:22:06.742263Z"
                writerId: 46ywv1h8dg6fgi94varqcy130c9gxap5
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 79
            "2":
                - 1
                - 5
                - 41
                - 53
                - 79
            "3":
                - 13
                - 16
            "4": 3.11.14
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
architecture:
    value: DenseNet121
epochs:
    value: 100
experiment_type:
    value: Squeeze-and-Excite
image_size:
    value: 224
