_wandb:
    value:
        cli_version: 0.24.0
        e:
            1m0q9cwlntqscktai9c3ms76x7eazgll:
                cpu_count: 48
                cpu_count_logical: 96
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "1247219048448"
                        used: "109971025920"
                email: arnaumarcosalmansa@gmail.com
                executable: /ghome/group06/miniconda3/envs/c3/bin/python
                git:
                    commit: e50ed30cb094f036f5056630e6d697e37da1062d
                    remote: https://github.com/MCV-C3/project-team-6.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-05a3ccca-10d1-a1b9-ad74-6a2e585188db
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-d79b2ec3-83fa-f792-9fde-fd304445f792
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-5b25a884-28ff-7d93-9a31-67a3b1fdc1cb
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-ae416e77-b12b-adee-0714-50d2ebf62fa4
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-68ef6434-456c-d5e3-d197-cbddab630194
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-1839c5e6-d9f4-6ef8-417d-8955e74919fc
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-9435860e-5399-a1cd-98e3-233e76cc5405
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-ac3b3009-3ea9-99f7-c6e4-482b39738ae1
                host: dcc3090
                memory:
                    total: "540873936896"
                os: Linux-5.15.0-88-generic-x86_64-with-glibc2.31
                program: /ghome/group06/workspace/project-team-6/Week4/train.py
                python: CPython 3.11.14
                root: .
                startedAt: "2026-01-18T16:47:52.161073Z"
                writerId: 1m0q9cwlntqscktai9c3ms76x7eazgll
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 9
                - 41
                - 79
                - 103
            "2":
                - 1
                - 9
                - 41
                - 79
                - 103
            "3":
                - 7
                - 13
                - 66
            "4": 3.11.14
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
architecture:
    value: Small LeNet
epochs:
    value: 500
image_size:
    value: 224
learning_rate:
    value: 0.0001
parameters:
    value: 24328
