_wandb:
    value:
        cli_version: 0.24.0
        e:
            sz27ziomdguo3p9kbcy8lwlnflj23zew:
                codePath: Week4/train.py
                codePathLocal: train.py
                cpu_count: 48
                cpu_count_logical: 96
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "1247219048448"
                        used: "109970374656"
                email: arnaumarcosalmansa@gmail.com
                executable: /ghome/group06/miniconda3/envs/c3/bin/python
                git:
                    commit: 0f26c952f40255e09c89817197d6e5c1fb5e2967
                    remote: https://github.com/MCV-C3/project-team-6.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-05a3ccca-10d1-a1b9-ad74-6a2e585188db
                host: dcc3090
                memory:
                    total: "540873936896"
                os: Linux-5.15.0-88-generic-x86_64-with-glibc2.31
                program: /export/home/group06/workspace/project-team-6/Week4/train.py
                python: CPython 3.11.14
                root: .
                slurm:
                    cluster_name: dcccvc
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "2"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: master
                    job_cpus_per_node: "2"
                    job_gid: "11006"
                    job_gpus: "3"
                    job_id: "100363"
                    job_name: mygpuhigh.sh
                    job_nodelist: dcc3090
                    job_num_nodes: "1"
                    job_partition: mhigh
                    job_qos: masterlow
                    job_uid: "11006"
                    job_user: group06
                    jobid: "100363"
                    localid: "0"
                    mem_per_node: "24576"
                    nnodes: "1"
                    node_aliases: (null)
                    nodeid: "0"
                    nodelist: dcc3090
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /export/home/group06/workspace/project-team-6/Week4
                    submit_host: dcc3090
                    task_pid: "2406731"
                    tasks_per_node: "2"
                    topology_addr: dcc3090
                    topology_addr_pattern: node
                    working_cluster: dcccvc:dcc3090:6817:9472:109
                startedAt: "2026-01-18T16:02:37.182736Z"
                writerId: sz27ziomdguo3p9kbcy8lwlnflj23zew
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.14
        t:
            "1":
                - 1
                - 9
                - 41
                - 103
            "2":
                - 1
                - 9
                - 41
                - 103
            "3":
                - 7
                - 13
                - 66
            "4": 3.11.14
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
architecture:
    value: Small LeNet
epochs:
    value: 500
image_size:
    value: 224
learning_rate:
    value: 0.0001
parameters:
    value: 24328
